// SPDX-License-Identifier: MIT
/*
 * H9 CAN protocol constants definition
 *
 * Copyright (C) 2024 Kamil Pałkowski
 *
 */

#ifndef H9DEF_H
#define H9DEF_H

enum {
    NODE_RESET_BY_UNKNOWN = 0,
    NODE_RESET_BY_POWER_ON,
    NODE_RESET_BY_WATCHDOG,
    NODE_RESET_BY_BROWN_OUT,
    NODE_RESET_BY_EXTERNAL_SOURCE,
};

enum {
    NODE_MCU_ATMEGA16M1 = 1,
    NODE_MCU_ATMEGA32M1,
    NODE_MCU_ATMEGA64M1,
    NODE_MCU_ATMEGA16C1,
    NODE_MCU_ATMEGA32C1,
    NODE_MCU_ATMEGA64C1,
    NODE_MCU_AT90CAN128,
    NODE_MCU_PIC18F46K80,
};

enum {
    NODE_MCU_F_2MHz = 1,
    NODE_MCU_F_4MHz,
    NODE_MCU_F_6MHz,
    NODE_MCU_F_8MHz,
    NODE_MCU_F_12MHz,
    NODE_MCU_F_16MHz,
};

enum {
    NODE_TYPE_STD_REGISTER = 0,
    NODE_HARDWARE_REVISION_STD_REGISTER,
    NODE_VERSION_STD_REGISTER,
    NODE_BUILD_INFO_STD_REGISTER,
    NODE_MCU_TYPE_STD_REGISTER,
    NODE_SN_STD_REGISTER,
    NODE_RESET_REASON_STD_REGISTER,
    NODE_POWER_SUPPLY_STD_REGISTER,
    NODE_MCU_TEMP_STD_REGISTER,
    NODE_ID_STD_REGISTER,
    NODE_STD_REGISTER_LAST
};

enum {
    H9FRAME_ERROR_INVALID_FRAME = 1,
    H9FRAME_ERROR_BOOTLOADER_UNSUPPORTED,
    H9FRAME_ERROR_UNSUPPORTED_OPERATION,
    H9FRAME_ERROR_UNSUPPORTED_REGISTER,
    H9FRAME_ERROR_INVALID_REGISTER,
    H9FRAME_ERROR_READ_ONLY_REGISTER,
    H9FRAME_ERROR_WRITE_ONLY_REGISTER,
    H9FRAME_ERROR_REGISTER_SIZE_MISMATCH
};

#endif //H9DEF_H
