// SPDX-License-Identifier: MIT
/*
 * H9 CAN protocol constants definition
 *
 * Copyright (C) 2024 Kamil Pałkowski
 *
 */

#ifndef H9DEF_H
#define H9DEF_H

enum {
    /* --- UNICAST --- */
    H9FRAME_TYPE_RES1 = 0,
    H9FRAME_TYPE_PAGE_START = 1,
    H9FRAME_TYPE_QUIT_BOOTLOADER = 2,
    H9FRAME_TYPE_PAGE_FILL = 3,
    H9FRAME_TYPE_RES2 = 4,
    H9FRAME_TYPE_PAGE_FILL_NEXT = 5,
    H9FRAME_TYPE_PAGE_WRITED = 6,
    H9FRAME_TYPE_PAGE_FILL_BREAK = 7,

    H9FRAME_TYPE_COMMAND_ERROR =  8,
    H9FRAME_TYPE_REG_VALUE =  9,
    H9FRAME_TYPE_SET_REG =  10,
    H9FRAME_TYPE_GET_REG =  11,
    H9FRAME_TYPE_SET_BIT =  12,
    H9FRAME_TYPE_CLEAR_BIT =  13,
    H9FRAME_TYPE_NODE_UPGRADE =  14,
    H9FRAME_TYPE_NODE_RESET =  15,

    /* --- SPECIAL BROADCAST --- */
    H9FRAME_TYPE_DISCOVER = 16,
    H9FRAME_TYPE_GROUP_RESET = 17,

    /* --- BROADCAST --- */
    H9FRAME_TYPE_NODE_FAULT = 18,
    H9FRAME_TYPE_REG_VALUE_BROADCAST = 19,
    H9FRAME_TYPE_NODE_HEARTBEAT = 20,
    H9FRAME_TYPE_NODE_INFO = 21,
    H9FRAME_TYPE_NODE_TURNED_ON = 22,
    H9FRAME_TYPE_BOOTLOADER_TURNED_ON = 23,

    H9FRAME_TYPE_NODE_SPECIFIC_BROADCAST0 = 24,
    H9FRAME_TYPE_NODE_SPECIFIC_BROADCAST1 = 25,
    H9FRAME_TYPE_NODE_SPECIFIC_BROADCAST2 = 26,
    H9FRAME_TYPE_NODE_SPECIFIC_BROADCAST3 = 27,
    H9FRAME_TYPE_NODE_SPECIFIC_BROADCAST4 = 28,
    H9FRAME_TYPE_NODE_SPECIFIC_BROADCAST5 = 29,
    H9FRAME_TYPE_NODE_SPECIFIC_BROADCAST6 = 30,
    H9FRAME_TYPE_NODE_SPECIFIC_BROADCAST7 = 31
};

enum {
    H9FRAME_FLAG_SINGE_FRAME = 0,
    H9FRAME_FLAG_MULTI_FRAME_FIRST = 1,
    H9FRAME_FLAG_MULTI_FRAME_MIDDLE = 2,
    H9FRAME_FLAG_MULTI_FRAME_LAST = 3
};

enum {
    NODE_RESET_BY_UNKNOWN = 0,
    NODE_RESET_BY_POWER_ON,
    NODE_RESET_BY_WATCHDOG,
    NODE_RESET_BY_BROWN_OUT,
    NODE_RESET_BY_EXTERNAL_SOURCE,
    NODE_RESET_BY_SOFTWARE,
};

enum {
    NODE_MCU_ATMEGA16M1 = 1,
    NODE_MCU_ATMEGA32M1,
    NODE_MCU_ATMEGA64M1,
    NODE_MCU_ATMEGA16C1,
    NODE_MCU_ATMEGA32C1,
    NODE_MCU_ATMEGA64C1,
    NODE_MCU_AT90CAN128,
    NODE_MCU_PIC18F46K80,
};

enum {
    NODE_MCU_F_2MHz = 1,
    NODE_MCU_F_4MHz,
    NODE_MCU_F_6MHz,
    NODE_MCU_F_8MHz,
    NODE_MCU_F_12MHz,
    NODE_MCU_F_16MHz,
};

enum {
    NODE_TYPE_STD_REGISTER = 0,
    NODE_HARDWARE_REVISION_STD_REGISTER,
    NODE_VERSION_STD_REGISTER,
    NODE_BUILD_INFO_STD_REGISTER,
    NODE_MCU_TYPE_STD_REGISTER,
    NODE_SN_STD_REGISTER,
    NODE_RESET_REASON_STD_REGISTER,
    NODE_POWER_SUPPLY_STD_REGISTER,
    NODE_MCU_TEMP_STD_REGISTER,
    NODE_ID_STD_REGISTER,
    NODE_STD_REGISTER_LAST
};

enum {
    H9FRAME_ERROR_INVALID_FRAME = 1,
    H9FRAME_ERROR_BOOTLOADER_UNSUPPORTED,
    H9FRAME_ERROR_UNSUPPORTED_OPERATION,
    H9FRAME_ERROR_UNSUPPORTED_REGISTER,
    H9FRAME_ERROR_INVALID_REGISTER,
    H9FRAME_ERROR_READ_ONLY_REGISTER,
    H9FRAME_ERROR_WRITE_ONLY_REGISTER,
    H9FRAME_ERROR_REGISTER_SIZE_MISMATCH
};

enum {
    H9FRAME_BROADCAST_ALL_GROUP = 0xffff,
};

enum {
    H9FRAME_TYPE_BIT_LENGTH = 5
};

enum {
    H9FRAME_FLAGS_BITS_LENGTH = 3
};

enum {
    H9FRAME_SEQNUM_BIT_LENGTH = 5
};

enum {
    H9FRAME_ID_BIT_LENGTH = 8
};

enum {
    H9FRAME_BROADCAST_GROUP_BIT_LENGTH = 16
};

#endif //H9DEF_H
